### ISSUE TITLE
special chars

### ISSUE THREAD

**Issue by marte-git** [anonimo345423/Lweb-Esercizio2#1]
ci sono occorrenze di problemi dovuti all'uso di caratteri non corrispondenti alla tabella usata sul server; guardate per esempio la citta' incantata nell'elenco dei film.
Potreste provare a sterilizzare questi problemi usando funzioni come htmlspecialchars .

**Comment by florin-git** [comment]
Ho aggiunto la funzione htmlspecialchars negli script 'cinemadb' e 'cinemadelete', in modo tale che vengano bene interpretati i titoli. Ho anche sistemato la città incantata mettendo al posto di 'à' l'entità &agrave;
Le modifiche sono state fatte al mio http://lweb.diag.uniroma1.it/~lweb17. Ora le farò anche qui su github.

**Comment by marte-git** [comment]
ok
